ALTER TABLE projects ADD COLUMN IF NOT EXISTS image_url TEXT NOT NULL DEFAULT '';

ALTER TABLE site_settings ADD COLUMN IF NOT EXISTS background_color TEXT NOT NULL DEFAULT '#f4f8fd';
ALTER TABLE site_settings ADD COLUMN IF NOT EXISTS text_color TEXT NOT NULL DEFAULT '#06132c';
ALTER TABLE site_settings ADD COLUMN IF NOT EXISTS accent_color TEXT NOT NULL DEFAULT '#fdc716';
ALTER TABLE site_settings ADD COLUMN IF NOT EXISTS whatsapp_number TEXT NOT NULL DEFAULT '923408144424';